version: '3'

services:
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    container_name: wp_db
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
    env_file:
      - ./db/config.env
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp_net
  
  wp:
    build: 
      context: ./wp
      dockerfile: Dockerfile
    container_name: wp_web
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./wp/wordpress:/var/www/html
    env_file:
      - ./wp/config.env
    environment:
      WORDPRESS_DB_HOST: wp_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress   
    networks:
      - wp_net

networks:
  wp_net: